name: Deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mvn clean package
      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo yum install -y java-17-openjdk
            mkdir -p ~/app
            scp target/*.jar ~/app/
            pkill -f "java -jar" || true
            cd ~/app
            nohup java -jar *.jar > app.log 2>&1 &