name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: seckill-demo
  CONTAINER_PORT: 8080

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: seckill-demo

      - name: Run tests
        run: mvn test
        working-directory: seckill-demo

      - name: Verify JAR
        run: ls -lh target/*.jar
        working-directory: seckill-demo

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifact
          path: seckill-demo/target/*.jar

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=commit-

      - uses: docker/build-push-action@v5
        with:
          context: ./seckill-demo
          file: ./seckill-demo/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/main' }}

  deploy:
    needs: docker-build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 停止并删除旧容器
            docker stop ${{ env.IMAGE_NAME }} || true
            docker rm ${{ env.IMAGE_NAME }} || true
            
            # 清理旧镜像
            docker image prune -f
            
            # 拉取最新镜像
            docker pull ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:main
            
            # 运行新容器
            docker run -d \
              --name ${{ env.IMAGE_NAME }} \
              -p ${{ env.CONTAINER_PORT }}:${{ env.CONTAINER_PORT }} \
              --restart unless-stopped \
              -e TZ=Asia/Shanghai \
              --memory=512m \
              --cpus=1.0 \
              ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:main
            
            # 检查容器状态
            echo "Container status:"
            docker ps -a | grep ${{ env.IMAGE_NAME }}
            
            # 检查容器日志
            echo "Container logs:"
            docker logs ${{ env.IMAGE_NAME }} --tail 50